# Generated by Django 3.2.5 on 2021-07-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_auto_20210710_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_course', to='syllabus.course'),
        ),
    ]
