# Generated by Django 3.2.5 on 2021-07-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_auto_20210710_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_user',
            new_name='user',
        ),
    ]
