# Generated by Django 3.2.5 on 2021-07-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_auto_20210710_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='user',
            new_name='enrolled_user',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='wishlist_user',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to='syllabus.course'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_course', to='syllabus.course'),
        ),
    ]
