# Generated by Django 3.2.5 on 2021-07-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0011_auto_20210710_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_user',
            new_name='user',
        ),
    ]
